# NumPy

## 1. Ndarray
ndarray 对象是用于存放同类型元素的多维数组。其内部有以下内容：
* 指向数据的指针
* 数据类型 (dtype)
* 表示数组形状的元组 (shape)
* 跨度元组 (strides)，表示前进到下一个元素需要“跨过”的字节数（可以是负数，表示反向移动）

In [1]:
'''
ndarray 的创建：
np.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    object: 数组
    dtype: 元素的数据类型, optional
        dtype 是一个对象: np.dtype(object, align=True, copy=False)
            object: 数据类型对象，可以用字符串表示
                int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
            align: 是否为类 C 的结构体
            copy: 是否复制 dtype 对象
            
        可选的数据类型有
            bool_, int_(long), intp(size_t), int8, int16, int32, int64, uint8, uint16, uint32, uint64,
            float_(float64), float16, float32, float64, complex_(complex128), complex64, complex128
    copy: 对象是否需要复制, optional
    order: 创建数组的样式, C 为行方向，F 为列方向, A 为任意方向, optional
    subok: 默认返回一个与基类型一致的数组
    ndmin: 指定生成数组的最小维度
'''
import numpy as np

dt1 = np.dtype(np.int32)
print(dt1)
dt2 = np.dtype('i4')
print(dt2)
print()
dt3 = np.dtype([('age', 'i1')])
arr1 = np.array([(10,), (20,), (30,)], dtype=dt3)
print(arr1)
print(arr1['age'])
print()
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
arr2 = np.array([
    ('Jack', 10, 60),
    ('John', 20, 80),
    ('Jane', 30, 96.5)
], dtype=student)
print(arr2)

int32
int32

[(10,) (20,) (30,)]
[10 20 30]

[(b'Jack', 10, 60. ) (b'John', 20, 80. ) (b'Jane', 30, 96.5)]


In [2]:
'''
properties of np.ndarray
    ndim: 数组的(轴的)维度数，相当于 len(shape)
    shape: 数组的各个维度
    size: 数组元素的总数，即 np.prod(shape)
    dtype: 数组元素的数据类型
    itemsize: 数组元素的字节数
    flags: 与内存布局相关的信息，如是否为 C 或 Fortran 连续存储；是否为只读
        C_CONTIGUOUS : 单一的 C 风格的连续段
        F_CONTIGUOUS : 单一的 Fortran 风格的连续段
        OWNDATA : 数组拥有其所使用的内存或从另一个对象中借用
        WRITEABLE : 数据区域可以被写入
        ALIGNED : 数据和所有元素适当地对齐到硬件上
        WRITEBACKIFCOPY : 其他数组的副本，如果此数组被释放，原数组内容会重新写入
    real: 元素实部(if complex)
    imag: 元素虚部(if complex)
    data: 实际存储数组元素的缓冲区
'''
import numpy as np

arr1 = np.arange(24)
print(arr1.ndim)
arr2 = arr1.reshape(2, 4, 3)
print(arr2.ndim)
print(arr2.shape)
print()
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3.flags)

1
3
(2, 4, 3)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 2. 数组创建

In [3]:
'''
np.empty(shape, dtype=float, order='C')
    shape: 数组形状    
    dtype: 元素的数据类型, optional
    order: 内存中的存储顺序，'C' | 'F' (行优先 | 列优先)
'''
import numpy as np

print(np.empty([3, 2], dtype=int))

[[0 0]
 [0 0]
 [0 0]]


In [4]:
'''
np.zeros(shape, dtype=float, order='C')
    shape: 数组形状    
    dtype: 元素的数据类型, optional
    order: 'C' 用于 C 的行数组，'F' 用于 Fortran 的列数组
'''
print(np.zeros((3, 2)))
print(np.zeros((3, 2), dtype=int))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]
 [0 0]]


In [5]:
'''
np.ones(shape, dtype=None, order='C')
    类似 np.zeros()
'''
print(np.ones(5))
print(np.ones((3, 2), dtype=int))

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]
 [1 1]]


In [6]:
'''
np.ones_like(a, dtype=None, order='K', subok=True, shape=None): 用于创建一个与给定数组具有相同形状的数组
    a: 基准数组
    dtype: 元素的数据类型
    order: 内存中的存储顺序，'C' | 'F' (行优先 | 列优先)，'K' 表示保持与基准数组相同
    subok: 是否返回子类对象
    shape: 数组形状
'''
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(np.zeros_like(a))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
'''
np.ones_like(a, dtype=None, order='K', subok=True, shape=None)
    类似 np.ones_like()
'''
print(np.ones_like(a))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
'''
np.asarray(a, dtype=None, order=None)
    a: 可迭代对象
    dtype: 元素的数据类型, optional
    order: 内存中的存储顺序，'C' | 'F' (行优先 | 列优先)
'''
print(np.asarray([1, 2, 3], dtype=float))
x = [(1, 2, 3), (4, 5)]
print(np.asarray(x, dtype=object))

[1. 2. 3.]
[(1, 2, 3) (4, 5)]


In [9]:
'''
np.frombuffer(buffer, dtype=float, count=-1, offset=0)
    buffer: 可以是任意对象，以流的形式读入
    dtype: 元素的数据类型, optional
    count: 读取的元素个数，-1 表示读取整个缓冲区
    offset: 读取的起始位置
'''
s = b'Hello World'
print(np.frombuffer(s, dtype='S1'))

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [10]:
'''
np.arange(start=0, stop, step=1, dtype=None)
    start: 起始值
    stop: 终止值
    step: 步长
    dtype: 元素的数据类型
'''
print(np.arange(5, dtype=float))
print(np.arange(10, 20, 2))

[0. 1. 2. 3. 4.]
[10 12 14 16 18]


In [11]:
'''
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None): 以等差数列创建
    start: 起始值
    stop: 终止值
    num: 元素个数
    endpoint: 是否包含终止值
    retstep: 是否显示间距
    dtype: 元素的数据类型
'''
print(np.linspace(1, 10, 10))
print(np.linspace(10, 20, 5, endpoint=False))
print(np.linspace(1, 10, 10, retstep=True))
print()
print(np.linspace(1, 10, 10).reshape([10, 1]))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[10. 12. 14. 16. 18.]
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


In [12]:
'''
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None): 以等比数列创建
    start: 起始值
    stop: 终止值
    num: 元素个数
    endpoint: 是否包含终止值
    base: 底数
    dtype: 元素的数据类型
'''
print(np.logspace(1., 2., 10))
print(np.logspace(0, 9, 10, base=2))

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


## 3. 切片与索引

### 3.1 切片

In [13]:
# 大体与列表切片相同
# ... 的用法
import numpy as np

arr = np.array([
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6]
])
print(arr[..., 1])  # 第二列
print(arr[1, ...])  # 第二行
print(arr[..., 1:])  # 第二列之后的元素

[3 4 5]
[3 4 5]
[[3 4]
 [4 5]
 [5 6]]


### 3.2 高级索引

In [14]:
# 整数数组索引
import numpy as np

arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(arr[[0, 1, 2], [0, 1, 0]])  # 索引为 (0, 0), (1, 1), (2, 0) 的元素

[1 4 5]


In [15]:
# 布尔索引
import numpy as np

arr1 = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])
print(arr1[arr1 > 5])
print()
arr2 = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(arr2[~np.isnan(arr2)])
print()
arr3 = np.array([1, 2 + 6j, 5, 3.5 + 5j])
print(arr3[np.iscomplex(arr3)])

[ 6  7  8  9 10 11]

[1. 2. 3. 4. 5.]

[2. +6.j 3.5+5.j]


In [16]:
# 花式索引
import numpy as np

arr1 = np.arange(10)
print(arr1[[0, 4, 6]])
print()
arr2 = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [2, 13, 14, 15],
    [6, 17, 18, 19],
    [0, 21, 22, 23],
    [4, 25, 26, 27],
    [8, 29, 30, 31],
])
print(arr2[[4, 2, 1, 7]])

[0 4 6]

[[ 6 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 8 29 30 31]]


## 4. Broadcast
rules:
* 让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。
* 输出数组的形状是输入数组形状的各个维度上的最大值。
* 如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
* 当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。

In [17]:
import numpy as np

a = np.array([
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])
b = np.array([1, 2, 3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


## 5. 迭代

In [18]:
import numpy as np

arr = np.arange(6).reshape(2, 3)
print(arr)
for i in np.nditer(arr):
    print(i, end=' ')

[[0 1 2]
 [3 4 5]]
0 1 2 3 4 5 

In [19]:
# 底层存储顺序
for i in np.nditer(arr.T):
    print(i, end=' ')
print()
for i in np.nditer(arr.T.copy(order='C')):
    print(i, end=' ')

0 1 2 3 4 5 
0 3 1 4 2 5 

In [20]:
# 迭代修改数组元素: op_flags 参数
arr = np.arange(0, 60, 5).reshape(3, 4)
print(arr)
for i in np.nditer(arr, op_flags=['readwrite']):
    i[...] = i * 2
print(arr)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [21]:
'''
flags 参数：
    c_index: 跟踪 C 顺序索引
    f_index: 跟踪 Fortran 顺序索引
    multi_index: 每次迭代跟踪一种索引
    external_loop: 返回的值是一维数组
'''
for i in np.nditer(arr, flags=['external_loop'], order='F'):
    print(i, end=' ')

[ 0 40 80] [10 50 90] [ 20  60 100] [ 30  70 110] 

## 6. 常见数组操作

### 6.1 修改数组形状

In [22]:
'''
np.reshape(arr, newshape, order='C')
    arr: 数组
    newshape: 整数或整数数组，新形状应与原有形状兼容
    order: 内存中的存储顺序，'C' | 'F' (行优先 | 列优先)
np.ndarray.flatten(order='C') -> 返回一份展平数组的拷贝（因此修改不会影响原数组）
np.ravel(a, order='C'): 将数组展平，修改会影响原数组
'''
import numpy as np

arr = np.arange(8).reshape(2, 4)
print(arr)
print(arr.flatten())

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]


### 6.2 数组翻转

In [23]:
'''
transpose(arr, axes=None)
    arr: 数组
    axes: 整数元组，指定轴的顺序，默认是原数组的倒序
np.ndarray.T: 相当于 self.transpose
'''
import numpy as np

arr = np.arange(12).reshape(2, 2, 3)
print(arr)
print(np.transpose(arr))
print(arr.shape)
print(np.transpose(arr, axes=(0, 2, 1)))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]
(2, 2, 3)
[[[ 0  3]
  [ 1  4]
  [ 2  5]]

 [[ 6  9]
  [ 7 10]
  [ 8 11]]]


In [24]:
'''
np.swapaxes(arr, axis1, axis2): 交换数组的两个轴
    arr: 数组
    axis1, axis2: 轴的索引
'''
arr = np.arange(8).reshape(2, 2, 2)
print(arr)
print(np.swapaxes(arr, 2, 0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [25]:
'''
np.expand_dims(arr, axis)
    arr: 数组
    axis: 整数，指定新轴插入的位置
'''
arr = np.array([
    [1, 2],
    [3, 4],
])
print(np.expand_dims(arr, axis=0).shape)

(1, 2, 2)


In [26]:
'''
np.squeeze(arr, axis=None)
    arr: 数组
    axis: 整数或整数元组，指定要压缩的轴，默认是所有长度为 1 的轴
'''
arr = np.arange(9).reshape(1, 3, 3)
print(np.squeeze(arr).shape)

(3, 3)


### 6.3 连接数组

In [27]:
'''
np.concatenate((a1, a2, ...), axis=0)
    a1, a2,...: 相同类型的数组
    axis: 整数，指定连接轴，默认是 0
'''
arr1 = np.array([
    [1, 2],
    [3, 4]
])
arr2 = np.array([
    [5, 6],
    [7, 8]
])
print(np.concatenate((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [28]:
'''
np.stack((a1, a2, ...), axis=0): 沿新轴堆叠数组
    a1, a2,...: 相同类型的数组
    axis: 整数，指定堆叠轴，默认是 0
'''
print(np.stack((arr1, arr2), axis=0))
print(np.stack((arr1, arr2), axis=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [29]:
# np.hstack(): 水平连接数组
print(np.hstack((arr1, arr2)))
# np.vstack(): 垂直连接数组
print(np.vstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 6.4 数组分割

In [30]:
'''
np.split(arr, indices_or_sections, axis=0)
    arr: 数组
    indices_or_sections: 如果是整数，按该数平均分割；如果是整数数组，按数组中的索引位置分割（左开右闭）
    axis: 分割轴，指定分割方向
np.hsplit()      水平分割
np.vsplit()      垂直分割
'''
import numpy as np

arr1 = np.arange(9)
print(np.split(arr1, 3))
print(np.split(arr1, [4, 7]))
print()
arr2 = np.arange(16).reshape(4, 4)
print(np.split(arr2, 2, axis=0))  # 水平切割
print(np.split(arr2, 2, axis=1))  # 垂直切割

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


### 6.5 数组元素操作

In [31]:
'''
np.append(arr, values, axis=None) -> 不改变原先数组
    arr: 数组
    values: 数组或标量，要插入的值
    axis: 整数，指定插入轴，默认是 None，此时返回的总是一维数组；axis=0 垂直插入，axis=1 水平插入
'''
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr)
print(np.append(arr, [7, 8, 9]))
print(np.append(arr, [[5, 5, 5], [6, 6, 6]], axis=1))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 5 5 5]
 [4 5 6 6 6 6]]


In [33]:
'''
np.insert(arr, obj, values, axis=None)
    arr: 数组
    obj: 在其之前插入的索引
    values: 数组或标量，要插入的值
    axis: 整数，指定插入轴
'''
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(np.insert(arr, 3, [7, 8], axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
'''
np.delete(arr, obj, axis=None)
    arr: 数组
    obj: 整数或整数数组，要删除的索引（可以切片）
    axis: 整数，指定删除轴
'''
arr = np.arange(12).reshape(3, 4)
print(arr)
newArr = np.delete(arr, 5)
print(newArr)
print(np.delete(newArr, np.s_[::2]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]
[ 1  3  6  8 10]


In [36]:
'''
np.unique(arr, return_index=False, return_inverse=False, return_counts=False)
    arr: 数组
    return_index: 返回新列表元素在原列表中的索引的列表
    return_inverse: 返回原列表中元素在新列表中的索引的列表
    return_counts: 返回每个元素在原列表中出现的次数
'''
arr = np.array([1, 2, 3, 2, 4, 1, 5])
print(arr)
u, index, inverse, count = np.unique(arr, return_index=True, return_inverse=True, return_counts=True)
print(u)
print(index)
print(u[inverse])
print(count)

[1 2 3 2 4 1 5]
[1 2 3 4 5]
[0 1 2 4 6]
[1 2 3 2 4 1 5]
[2 2 1 1 1]


## 7. 函数

### 7.1 字符串函数
针对 dtype 为 np.string_ 或 np.unicode_ 的数组

In [37]:
'''
np.char.add(str1, str2): 对两个字符串数组对应元素进行拼接
np.char.multiply(str, repeats): 字符串的多重连接
np.char.center(str, width, fillchar=' '): 字符串居中
np.char.capitalize(str): 字符串首字母大写
np.char.title(str): 字符串每个单词首字母大写
np.char.lower(str): 字符串全部转为小写
np.char.upper(str): 字符串全部转为大写
np.char.split(str, sep=None, maxsplit=None): 分割字符串，并返回数组
np.char.splitlines(str, keepends=False): 分割字符串中的行，并返回数组
np.char.strip(str, chars=None): 去除字符串两端的特定字符
np.char.join(sep, str): 通过指定分隔符连接数组中的元素
np.replace(str, old, new, count=None): 替换字符串中的子串
np.char.decode(str, encoding='utf-8', errors='strict'): 对数组中的元素依此调用 str.decode
np.char.encode(str, encoding='utf-8', errors='strict'): 对数组中的元素依此调用 str.encode
'''
from numpy import char

print(char.add(["hello", "hi"], ["abc", "xyz"]))
print(char.multiply("hello ", 3))
print(char.center("hello", 20, fillchar='*'))
print(char.split("www.baidu.com", sep="."))
print(char.splitlines("hello\nworld\n"))
print(char.strip(["java", "admin"], 'a'))
print(char.join(':', "hello"))
print(char.replace("hello world", "l", "L"))

['helloabc' 'hixyz']
hello hello hello 
*******hello********
['www', 'baidu', 'com']
['hello', 'world']
['jav' 'dmin']
h:e:l:l:o
heLLo worLd


### 7.2 数学函数

### 7.2.1 三角函数

In [38]:
'''
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x): 将弧度转换为角度
'''
import numpy as np

print(np.degrees(np.tan(np.pi / 4)))

57.295779513082316


### 7.2.2 舍入函数

In [41]:
'''
np.around(arr, decimals=0)
    arr: 数组
    decimals: 要保留的小数位数; 如果为负数，则四舍五入到小数点左边的位数
np.floor(arr): 向下取整
np.ceil(arr): 向上取整
'''
import numpy as np

arr = np.array([1.0, 5.55, 123, 0.567, 25.532])
print(arr)
print(np.around(arr))
print(np.around(arr, decimals=1))
print(np.around(arr, decimals=-1))

[  1.      5.55  123.      0.567  25.532]
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


### 7.3 算数函数

In [44]:
'''
np.add(arr1, arr2): 数组元素相加
np.subtract(arr1, arr2): 数组元素相减
np.multiply(arr1, arr2): 数组元素相乘
np.divide(arr1, arr2): 数组元素相除
np.reciprocal(arr): 数组元素求倒数
np.power(arr1, arr2): 数组元素求幂
np.mod(arr1, arr2): 数组元素求模
'''
import numpy as np

arr1 = np.arange(9, dtype=np.float_).reshape(3, 3)
arr2 = np.array([2, 2, 2], dtype=np.float_)
print(arr1)
print(arr2)
print()
print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))
print(np.reciprocal(arr2))
print(np.power(arr1, arr2))
print(np.mod(arr1, arr2))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[2. 2. 2.]

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[-2. -1.  0.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]]
[[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]]
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]
[0.5 0.5 0.5]
[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]
[[0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]


### 7.4 统计函数

In [47]:
'''
np.amin(arr, axis=None, out=None, keepdims=np._NoValue, initial=np._NoValue, where=np._NoValue)
    arr: 数组
    axis: 指定在哪个轴上取最小，可以是整数，也可以是整数数组；默认是 None，表示沿所有轴
    out: 指定结果的存储位置，默认是 None，表示输出到新数组
    keepdims: 是否保持维度，默认是 False，表示去除维度为 1 的轴
    initial: 指定初始值
    where: 布尔数组，指定仅考虑满足条件的元素
np.amax() 同理
np.argmin(): 返回最小值的索引
np.argmax(): 返回最大值的索引
np.ptp(): 参数相同，计算极差
'''
import numpy as np

arr = np.array([
    [3, 7, 5],
    [8, 4, 3],
    [2, 4, 9]
])
print(arr)
print(np.amin(arr, 1))
print(np.amin(arr, 0))
print(np.amax(arr))
print(np.ptp(arr))

[[3 7 5]
 [8 4 3]
 [2 4 9]]
[3 3 2]
[2 4 3]
9
7


In [50]:
'''
np.percentile(arr, q, axis): 计算数组的 q 分位数
    arr: 数组
    q: 百分位数, 0 ~ 100 之间
    axis: 指定在哪个轴上计算
np.median(arr, axis=None, out=None, overwrite_input=False, keepdims=np._NoValue): 计算数组的中位数
    arr: 数组
    axis: 指定在哪个轴上计算
    out: 指定结果的存储位置
    overwrite_input: 是否允许使用输入数组的内存，可以提高性能，但可能会改变输入数组的值
    keepdims: 是否保持维度
np.mean(arr, axis=None, dtype=None, out=None, keepdims=np._NoValue): 算术平均
np.average(arr, axis=None, weights=None, returned=False): 加权平均
    arr: 数组
    axis: 指定在哪个轴上计算
    weights: 权重数组，不指定相当于求算术平均
    returned: 是否同时返回加权平均值和权重总和
np.std(arr): 计算数组的标准差
np.var(arr): 计算数组的方差
'''
arr = np.array([
    [10, 7, 4],
    [3, 2, 1]
])
print(np.percentile(arr, 50))  # 中位数
print(np.percentile(arr, 50, axis=1))  # 行中位数
print(np.mean(arr))
weights = [
    [1, 2, 3],
    [3, 2, 1]
]
print(np.average(arr, weights=weights, returned=True))
print(np.std(arr))
print(np.var(arr))

3.5
[7. 2.]
4.5
(4.166666666666667, 12.0)
3.095695936834452
9.583333333333334


### 7.5 排序、条件筛选函数

In [57]:
'''
np.sort(arr, axis=-1, kind='quicksort', order=None) -> 返回排序后的数组副本
    arr: 数组
    axis: 指定在哪个轴上排序
    kind: 排序算法，'quicksort' | 'mergesort' | 'heapsort'
    order: 排序字段
np.argsort(): 返回从小到大的索引值
np.lexsort(): 对多个序列进行排序，具有优先级
np.sort_complex(arr): 排序复数数组, 先按实部，再按虚部
np.partition(arr, kth, axis=-1, kind='introselect', order=None): 指定一个数，对数组进行分区
'''
import numpy as np

arr = np.array([5, 6, 13, 3, 8, 2, 11])
print(arr)
print(np.sort(arr))
print(arr[np.argsort(arr)])
print()
names = ['Alice', 'Bob', 'Charlie', 'David']
ages = [30, 40, 30, 20]
index = np.lexsort((ages, names))  # 先排 names，再排 ages
print(index)
print([names[i] + ', ' + str(ages[i]) for i in index])

[ 5  6 13  3  8  2 11]
[ 2  3  5  6  8 11 13]
[ 2  3  5  6  8 11 13]

[0 1 2 3]
['Alice, 30', 'Bob, 40', 'Charlie, 30', 'David, 20']


In [58]:
'''
np.nonzero(arr) ->非零元素的索引
np.where(): 条件筛选 -> 满足条件的元素的索引
np.extract(): 条件筛选 -> 满足条件的元素
'''
arr1 = np.array([
    [30, 40, 0],
    [0, 20, 10],
    [50, 0, 60]
])
print(arr1[np.nonzero(arr1)])
print()
arr2 = np.arange(9).reshape(3, 3)
print(arr2)
print(arr2[np.where(arr2 > 5)])
print(np.extract(np.mod(arr2, 2) == 0, arr2))

[30 40 20 10 50 60]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7 8]
[0 2 4 6 8]


## 8. 线性代数

In [62]:
'''
np.dot(a, b, out=None): 矩阵乘法    与 np.matmul(a, b) 等价
np.vdot(a, b): 向量点乘, 高维会展开
np.inner(a, b): 内积，高维只计算最后一维
np.linalg.det(arr): 计算行列式
np.linalg.eig(arr): 计算特征值和特征向量
np.linalg.inv(arr): 计算矩阵的逆
np.linalg.solve(A, b): 解线性方程组
np.linalg.norm(arr, ord=None, axis=None, keepdims=False)
    arr: 数组
    ord: 范数类型，整数，默认为 2
'''
import numpy as np
from numpy import linalg as la

a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [11, 12],
    [13, 14]
])
print(np.dot(a, b))
print(np.vdot(a, b))
print(np.inner(a, b))
print(la.det(a))
result = la.eig(a)
print(result[0])  # 特征值
print(result[1])  # 特征向量
print(la.inv(a))
print(la.solve(a, np.array([5, 6])))

[[37 40]
 [85 92]]
130
[[35 41]
 [81 95]]
-2.0000000000000004
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[-4.   4.5]
